= Log

The first commits to this will be pretty scattered. As my usage becomes more consistent, commits will match the approximate time of the activity.

Spent time this morning investigating WebRTC. I was really looking for a way to monitor network connection health so I could display this on my mobile apps. This is part of my ideas around providing more diagnostic information within my apps. The debug view in Powercal was my first dive into this.

When I host my next Engineering Practice Fridays session, I want to try remote mob programming. Zoom and Bluejeans are candidates to replace Google Hangouts to increase the video chat quality. Teletype for Atom and Tuple (Mac only remote pairing tool) were suggested by Isaac for screen sharing tools.

What's left is a way to switch drivers. Committing to a branch has variable friction. If the mob programming use case wasn't considered by the team, it's quite likely that even branch commits have pre-commit hooks that could reject work in progress. I am currently experimenting with a tar plus Google Bucket solution that should reliably work for just about any setup. My Broad `dmohs` repo is the first attempt.

I read part of an article the other day https://reason.com/2019/08/01/despite-what-democrats-said-at-their-debate-were-not-heading-toward-climate-apocalypse/[[1]] about how maybe the impending climate changes don't necessarily spell doom for the human race.

This is neat: https://www.millionshort.com - search the less search-optimized sites.

Is this Jesse? https://uvwx.github.io/hierarchy.html[On a hierarchy of software engineering discourse]

I've been reading Reddit. Possibly a bad move, but I did find a great programming article. Using a font to display numbers with comma separators. It's elegant. https://blog.janestreet.com/commas-in-big-numbers-everywhere/

Yay for writing code to solve a problem and thus trigger a discussion. This minimal app for switching windows on OSX lead to a nice discussion about window management. https://news.ycombinator.com/item?id=21253850

Like re-captcha, but you earn money. https://www.hcaptcha.com

Manage your domains agnostic of registrar. link:https://www.bestdomainportfoliomanager.com/#!/start[]
Discussion. https://bookface.ycombinator.com/posts/43161

Shared ephemeral state for horizonally-scaled APIs? https://cloud.google.com/memorystore/docs/redis/

Duplicate a tab in Safari: Command + L and then Command + Return (or Enter)

Since I've been thinking about request-blocking services such as rate limit managers, I've been thinking about latency. I'm seeing around 80ms for HTTPS and 40ms for HTTP, using curl to time the requests. Apple.com is 30 and 60, respectively, perhaps due to CDN. I was curious if Go would be better on AppEngine, so I deployed a simple app and tested it. I got around 70ms and 120ms response times for HTTP and HTTPS, respectively. Worse.
